# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-22 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171122_1912'),
    ]

    operations = [
    ]
